name: data
on:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch: {}
  push:
    branches:
      - main
      - dev
      - flat-data
    paths:
      - .github/workflows/flat.yml
      - data/postprocess.js
jobs:
  scheduled:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: ${{secrets.ALCHEMY_BASEURL}}/getNFTsForCollection?contractAddress=${{secrets.CONTRACT_ADDRESS}}&startToken=0&withMetadata=true
          downloaded_filename: data/nftList.json
          postprocess: data/postprocess.js
          mask: '["${{secrets.ALCHEMY_BASEURL}}"]'
