name: data
on:
  schedule:
    - cron: 0 */4 * * *
  workflow_dispatch: {}
  push:
    branches:
      - dev
      - main
    paths:
      - .github/workflows/flat.yml
      - data/postprocess.js
jobs:
  scheduled:
    environment: Production
    runs-on: ubuntu-latest
    env:
      ALCHEMY_BASEURL: ${{secrets.ALCHEMY_BASEURL}}
      CONTRACT_ADDRESS: ${{secrets.CONTRACT_ADDRESS}}
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: ${{secrets.ALCHEMY_BASEURL}}/getNFTsForCollection?contractAddress=${{secrets.CONTRACT_ADDRESS}}&startToken=0&withMetadata=true
          downloaded_filename: data/nftList.json
          postprocess: data/postprocess.js
          mask: '["${{secrets.ALCHEMY_BASEURL}}"]'
      - name: Trigger build
        uses: amondnet/vercel-action@19
        with:
          vercel-token: ${{ secrets.VERCEL_DEPLOY_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-args: ${{ github.ref == 'refs/heads/main' && '--prod' || '' }}
